#!/bin/bash
set -e

BINUTILS_VERSION=2.28
GCC_VERSION=7.1.0
BOOST_VERSION=1.62.0
PKG_CONFIG_VERSION=0.29.1
CCACHE_VERSION=3.3.3
CMAKE_VERSION=3.6.3
CMAKE_MAJOR_VERSION=3.6
ZLIB_VERSION=1.2.8
BZIP2_VERSION=1.0.6
OPENSSL_VERSION=1.0.2j
CURL_VERSION=7.51.0
SQLITE_VERSION=3150100
SQLITE_YEAR=2016
OSARCH=$(uname -i)

source /hbb_build/functions.sh
source /hbb_build/activate_func.sh

SKIP_TOOLS=${SKIP_TOOLS:-false}
SKIP_LIBS=${SKIP_LIBS:-false}
SKIP_FINALIZE=${SKIP_FINALIZE:-false}

SKIP_PKG_CONFIG=${SKIP_PKG_CONFIG:-$SKIP_TOOLS}
SKIP_CCACHE=${SKIP_CCACHE:-$SKIP_TOOLS}
SKIP_CMAKE=${SKIP_CMAKE:-$SKIP_TOOLS}

SKIP_ZLIB=${SKIP_ZLIB:-$SKIP_LIBS}
SKIP_BOOST=${SKIP_BOOST:-$SKIP_LIBS}
SKIP_BZIP2=${SKIP_BZIP2:-$SKIP_LIBS}
SKIP_OPENSSL=${SKIP_OPENSSL:-$SKIP_LIBS}
SKIP_CURL=${SKIP_CURL:-$SKIP_LIBS}
SKIP_SQLITE=${SKIP_SQLITE:-$SKIP_LIBS}

MAKE_CONCURRENCY=${MAKE_CONCURRENCY:-2}
VARIANTS='exe exe_gc_hardened shlib'
export PATH=/hbb/bin:$PATH


